import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AdminProvider } from "./context/AdminContext";
import Navbar from "./components/Navbar/Navbar";
import { QuizProvider } from "./context/QuizContext";
import { EssayProvider } from "./context/EssayContext";
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teacher Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminProvider>
          <QuizProvider>
            <EssayProvider>
              <Navbar />
              <main className="min-h-screen bg-gray-50">
                {children}
              </main>
              <Toaster position="top-center" richColors />
            </EssayProvider>
          </QuizProvider>
        </AdminProvider>
      </body>
    </html>
  );
}